// <auto-generated />
namespace MovieLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tookoffaprop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tookoffaprop));
        
        string IMigrationMetadata.Id
        {
            get { return "202001131932042_took off a prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
